### ISSUE TITLE
Fortify SSC in Version 16.20

### ISSUE THREAD

**Issue by T1mey** [fod-dev/FoDBugTrackerUtility#25]
Is there a way to use the tool with Fortify in version 16.20 ?

**Comment by rsenden** [comment]
Recent versions of the utility have been mostly tested with SSC 17.10 (and some limited testing has been done with SSC 17.20). The utility utilizes the SSC REST API; as far as I know there have been no major changes in the SSC REST API so possibly the utility should work fine with SSC 16.20 as well. This will need to be tested though. Are there any specific issues you are running in to, for example error messages originating from SSC?

**Comment by T1mey** [comment]
It seems that SSC values are read. even with version 16.20

**Comment by rsenden** [comment]
Thanks for the update, closing this issue then
