### ISSUE TITLE
SSC: Make extra fields available for field mapping

### ISSUE THREAD

**Issue by rsenden** [fod-dev/FoDBugTrackerUtility#28]
Some customers would like to be able to submit additional details to the bug tracker, like application and version name, build label and audit comments.

At the moment, there is a work-around for application and version name, but not for additional vulnerability details. It would be nice if we could add on-demand properties for all vulnerability-related information.

For application and version name, the work-around is as follows:
```xml
<bean class="com.fortify.processrunner.ssc.appversion.SSCApplicationVersionNameBasedContextGenerator">
    <property name="applicationVersionNameMappings"><map>
        <entry key=".*" value="applicationName=${project.name},versionName=${name}"/>
    </map></property>
</bean>

<bean class="com.fortify.processrunner.common.bugtracker.issue.BugTrackerFieldConfiguration">
    <property name="fields"><map>
        ...
        <entry key="application" value="${#ctx.applicationName}"/>
        <entry key="version" value="${#ctx.versionName}"/>
    </map></property>
</bean>
```

**Comment by indratan** [comment]
hi rsenden, I am sorry I am posting here. I just couldn't find your direct email anywhere. we need help in this utility. we have contacted microFocus support, and not getting help so far. our requirement is very simple, we just want to try submitting records automatically from SSC to JIRA. nothing fancy. would you be able to assist or know who can? or give us pointers on where to post questions (if you can't support). thank you very much.
Indra Tanudjaja
FRB-SF
indra.tanudjaja@sf.frb.org

**Comment by rsenden** [comment]
This has already been implemented, and the approach for getting application version details has been simplified.
