### ISSUE TITLE
Provide syncing bugs by release name just like release id

### ISSUE THREAD

**Issue by RajanGup** [fod-dev/FoDBugTrackerUtility#29]
Similar to the way utility can be run by using a release ID provide the ability to run it by using release name.
Yes ID can be used but it is more complicated as it has to get the user to go get the Id from portal and most people may not know where to find it and also does not help visually especially when someone does not full end to end automation  .

**Comment by rsenden** [comment]
Support for selecting a single application release by name has been added to the master branch, and will be included in the next release.
