### ISSUE TITLE
"Add Existing Bugs"

### ISSUE THREAD

**Issue by raphaelhagi** [fod-dev/FoDBugTrackerUtility#31]
Please help,

I ran my bugtrackerutility as follows:

java -jar FortifyBugTrackerUtility-3.5.jar -logLevel TRACE -configFile SSCToJira.xml -JiraBaseUrl https://demofortify.atlassian.net -JiraPassword "*****" -JiraUserName "*****" -JiraProjectKey RAB

I´ve added the tag <property name="addNativeBugLink" value="true"/> to issue 30 i´ve opened yesterday, but no I can´t send any bug to my JIRA, the output from console was:

[main] [process] Logging to FortifyBugTrackerUtility-3.5.log with level TRACE
[main] [Process] Using Spring configuration file SSCToJira.xml
[main] [process] Logging to FortifyBugTrackerUtility-3.5.log with level TRACE
[main] [SSC] Obtained access token, expiring at Sat Mar 02 14:00:52 UTC 2019
[main] [SSC] Application version **Rabbit:1 excluded; doesn't have bug tracker Add Existing Bugs**
[main] [SSC] Application version Webgoat:Versπo 1 excluded; doesn't have bug tracker Add Existing Bugs
[main] [Process] Processing complete

What I´ve done wrong? I search my entire application version profile for this "Add Existing Bugs" option, plugins with no success.

Thanks!

**Comment by rsenden** [comment]
Hi,

The FortifyBugTrackerUtility distribution zip contains the 'Add Existing
Bugs' plugin for SSC. You will need to install this plugin in SSC
(Administration->Bug Tracker Plugins), and then enable this plugin for your
application version (Profile->Bug Tracker).

Best regards,
Ruud Senden

**Comment by raphaelhagi** [comment]
I don't find it. Where is it located?

I've downloaded FortifyBugTrackerUtility-3.5-dist.zip

**Comment by raphaelhagi** [comment]
Okay, is this: FoDBugTrackerUtility-master.zip\FoDBugTrackerUtility-master\ssc-bugtracker-add-existing-bug\lib\fortify-public-17.10.0.0158.jar ?

**Comment by raphaelhagi** [comment]
My previous message, my mistake.
I'm trying to compile the FortifyBugTrackerUtility compile it using Maven (mvn).

Seems to be some errors with pom.xml file, related to some references. I've tried to move do jitpack, but without sucess:

PS C:\temp\FoDBugTrackerUtility> mvn -U
[INFO] Scanning for projects...
Downloading from jitpack.io: https://jitpack.io/com/fortify/client/api/client-api-master/4.7/client-api-master-4.7.pom
Downloading from central: https://repo.maven.apache.org/maven2/com/fortify/client/api/client-api-master/4.7/client-api-m
aster-4.7.pom
**[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact com.fortify.client.api:client-api-master:pom:4.7 in jitpack.i
o (https://jitpack.io) @ line 81, column 16
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.fortify.bugtracker:bugtracker-root:3.6-SNAPSHOT (C:\Temp\FoDBugTrackerUtility\pom.xml) has 1 e
rror
[ERROR]     Non-resolvable import POM: Could not find artifact com.fortify.client.api:client-api-master:pom:4.7 in jitpa
ck.io (https://jitpack.io) @ line 81, column 16 -> [Help 2]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException**
PS C:\temp\FoDBugTrackerUtility>

**Comment by raphaelhagi** [comment]
With the original pom.xml file:

[INFO] Scanning for projects...
Downloading from FortifyMavenRepo: https://raw.githubusercontent.com/rsenden/FortifyMavenRepo/master/com/fortify/client/
api/client-api-master/4.8-SNAPSHOT/maven-metadata.xml
Downloading from FortifyMavenRepo: https://raw.githubusercontent.com/rsenden/FortifyMavenRepo/master/com/fortify/client/
api/client-api-master/4.8-SNAPSHOT/client-api-master-4.8-SNAPSHOT.pom
**[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Could not find artifact com.fortify.client.api:client-api-master:pom:4.8-SNAPSHOT in
FortifyMavenRepo (https://raw.githubusercontent.com/rsenden/FortifyMavenRepo/master) @ line 85, column 16
 @
[ERROR] The build could not read 1 project -> [Help 1]
[ERROR]
[ERROR]   The project com.fortify.bugtracker:bugtracker-root:3.6-SNAPSHOT (C:\Temp\FoDBugTrackerUtility\pom.xml) has 1 e
rror
[ERROR]     Non-resolvable import POM: Could not find artifact com.fortify.client.api:client-api-master:pom:4.8-SNAPSHOT
 in FortifyMavenRepo (https://raw.githubusercontent.com/rsenden/FortifyMavenRepo/master) @ line 85, column 16 -> [Help 2
]
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException**

**Comment by raphaelhagi** [comment]
Hello,

It finally works, I cloned the 3.5 version repo, last commited 7 months ago and then compile it with Maven.

**Comment by raphaelhagi** [comment]
Hello,

To close this issue: 

1) Download de latest version (3.5), or clone it with git;
2) Compile the project with Maven, in same directory, use mvn compile
3) Access SSC with admin user, go to Administration
4) Open "Plugins", and then "Bug Tracking"
5) Click the "New" button, and send your .jar compiled with maven (FoDBugTrackerUtility-bugtracker-root-3.5\ssc-bugtracker-add-existing-bug\target\ssc-bugtracker-add-existing-bug-3.5.jar)
6) Go to your application profile and enable "Add Existing Bug"

![image](https://user-images.githubusercontent.com/14099181/53659266-e12aed00-3c39-11e9-93d3-f105a0fe8602.png)

It's done!

Thanks for your support rsenden.

**Comment by rsenden** [comment]
Hi,

Good to hear that you managed to make this work. The 'Add Existing Bugs' plugin should have been included in the FortifyBugTrackerUtility distribution zip file, but apparently it wasn't. I will fix this for the next release, so you will no longer need to build the project yourself.
